import type {Metadata, Viewport} from "next";
import {Inter} from "next/font/google";
import "../../app/globals.css";
import {ThemeProvider} from "@/components/theme-provider";
import {Separator} from "@/components/ui/separator";
import {cn} from "@/lib/utils";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const viewport: Viewport = {
    initialScale: 1,
    width: 'device-width'
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
        <body className={cn(`${inter.className} antialiased`, 'flex flex-col h-dvh')}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <header
                className="fixed top-0 left-0 right-0 flex flex-row items-center justify-center px-6 py-3 gap-4 md:gap-6 w-full bg-background/80 backdrop-blur-sm z-10">
                {/*<HeaderButton href='/tracks'>Tracks</HeaderButton>*/}
                {/*<HeaderButton href='/albums'>Albums</HeaderButton>*/}
                {/*<HeaderButton href='/artists'>Artists</HeaderButton>*/}
            </header>
            <Separator className="fixed top-[64px]"/>
            <main className="flex-grow mt-[64px]">
                {children}
            </main>
        </ThemeProvider>
        </body>
        </html>
    );
}